default: &default
  adapter: postgresql
  pool: 5
  username: <%= ENV['POSTIT_DATABASE_USERNAME'] %>
  password: <%= ENV['POSTIT_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: "postit_development"

test:
  <<: *default
  database: "postit_test"

production:
  <<: *default
  database: "postit_production"
